# Generated by Django 5.0.7 on 2024-08-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='imagealaune',
            field=models.ImageField(upload_to='static/images/articles/'),
        ),
        migrations.AlterField(
            model_name='auteur',
            name='photo',
            field=models.ImageField(upload_to='static/images/auteur/'),
        ),
    ]
