# Generated by Django 5.0.7 on 2024-08-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_alter_auteur_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='imagealaune',
            field=models.ImageField(upload_to='images/articles/'),
        ),
        migrations.AlterField(
            model_name='auteur',
            name='photo',
            field=models.ImageField(upload_to='images/auteurs/'),
        ),
    ]
