# Generated by Django 5.0.7 on 2024-08-17 02:19

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_articles_imagealaune_alter_auteur_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='imagealaune',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='sites/static/'), upload_to='images/articles/'),
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.articles')),
            ],
        ),
    ]
