# Generated by Django 5.0.7 on 2024-10-30 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_alter_articles_contenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='image',
        ),
    ]
