# Generated by Django 5.0.7 on 2024-10-31 00:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_remove_articles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='contenu',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
